language: dart

sudo: false

dart:
  - dev
  - stable

dart_task:
  - test: --platform vm
  - dartfmt: -l 120

cache:
  directories:
    - $HOME/.pub-cache

script:
  # - ./bin/fetch-configlet # TODO
  # - ./bin/configlet .     # TODO
