language: dart

sudo: false

dart:
  - dev
  - stable

dart_task:
  - test: --platform vm

cache:
  directories:
    - $HOME/.pub-cache

before_script:
  - pub run dart_style:format -l 120 -n .

script:
  # - ./bin/fetch-configlet # TODO
  # - ./bin/configlet .     # TODO
